apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartorder-server
  labels:
    app: smartorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartorder
  template:
    metadata:
      labels:
        app: smartorder
    spec:
      containers:
        - name: controller
          imagePullPolicy: Always
          image: smartorder/server:latest
          env:
            - name: APP_MODE
              value: CONTROLLER
          lifecycle:
            preStop:
              httpGet:
                path: "/api/health/down/"
                port: 5000
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: "/api/health/check/"
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: smartorder-config
              mountPath: "/etc/uwsgi.ini"
              subPath: uwsgi.ini
              readOnly: true
            - name: smartorder-config
              mountPath: "/etc/config/app.properties"
              subPath: app.properties
              readOnly: true
            - name: smartorder-config
              mountPath: "/etc/config/env.sh"
              subPath: env.sh
              readOnly: true
            - name: smartorder-secrets
              mountPath: "/etc/config/secrets.properties"
              subPath: secrets.properties
              readOnly: true
          ports:
            - containerPort: 5000
        - name: denormalizer
          imagePullPolicy: Always
          image: smartorder/server:latest
          env:
            - name: APP_MODE
              value: DENORMALIZER
          lifecycle:
            preStop:
              httpGet:
                path: "/api/health/down/"
                port: 5001
          livenessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: "/api/health/check/"
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: smartorder-config
              mountPath: "/etc/uwsgi.ini"
              subPath: uwsgi.ini
              readOnly: true
            - name: smartorder-config
              mountPath: "/etc/config/app.properties"
              subPath: app.properties
              readOnly: true
            - name: smartorder-config
              mountPath: "/etc/config/env.sh"
              subPath: env.sh
              readOnly: true
            - name: smartorder-secrets
              mountPath: "/etc/config/secrets.properties"
              subPath: secrets.properties
              readOnly: true
          ports:
            - containerPort: 5001
        - name: prediction
          imagePullPolicy: Always
          image: smartorder/server:latest
          env:
            - name: APP_MODE
              value: PREDICTION
          lifecycle:
            preStop:
              httpGet:
                path: "/api/health/down/"
                port: 5002
          livenessProbe:
            tcpSocket:
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: "/api/health/check/"
              port: 5002
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: smartorder-config
              mountPath: "/etc/uwsgi.ini"
              subPath: "uwsgi.ini"
              readOnly: true
            - name: smartorder-config
              mountPath: "/etc/config/app.properties"
              subPath: "app.properties"
              readOnly: true
            - name: smartorder-config
              mountPath: "/etc/config/env.sh"
              subPath: env.sh
              readOnly: true
            - name: smartorder-secrets
              mountPath: "/etc/config/secrets.properties"
              subPath: secrets.properties
              readOnly: true
          ports:
            - containerPort: 5002
      volumes:
        - name: smartorder-config
          configMap:
            name: smartorder-config
        - name: smartorder-secrets
          secret:
            secretName: smartorder-secrets
