# This file is used only for the local development, all
# deployed AWS environments use kubernetes for container 
# orchestration
version: '3'

services:

  postgres_service:
   container_name: postgresql
   restart: always
   image: postgres:10.5
   volumes:
     - postgres-data:/var/lib/postgresql/data
     - ./postgresql/init:/docker-entrypoint-initdb.d
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  controller:
    container_name: controller
    restart: on-failure
    image: controller
    build:
      context: ./dsdp
      dockerfile: Dockerfile.app.local
    ports:
      - "5000:5000"
    environment:
        - PYTHONPATH=.
        - FLASK_APP=wsgi.py
        - FLASK_DEBUG=1
        - CONFIG_PATH=config/local
        - APP_MODE=CONTROLLER
    depends_on:
      - redis
      - postgres_service
      - flower

  denormalizer:
    container_name: denormalizer
    restart: on-failure
    image: denormalizer
    build:
      context: ./dsdp
      dockerfile: Dockerfile.app.local
    ports:
      - "5001:5001"
    volumes:
      - ./tmp:/tmp
    environment:
        - PYTHONPATH=.
        - FLASK_APP=wsgi.py
        - FLASK_DEBUG=1
        - CONFIG_PATH=config/local
        - APP_MODE=DENORMALIZER

    depends_on:
      - postgres_service
      - redis
      - flower

  prediction:
    container_name: prediction
    restart: on-failure
    image: prediction
    build:
      context: ./dsdp
      dockerfile: Dockerfile.app.local
    ports:
      - "5002:5002"
    environment:
      - PYTHONPATH=.
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - CONFIG_PATH=config/local
      - APP_MODE=PREDICTION

    depends_on:
      - postgres_service
      - redis
      - flower

  flower:
    container_name: flower
    restart: on-failure
    image: flower
    build:
      context: ./dsdp
      dockerfile: Dockerfile.flower
    environment:
      - PYTHONPATH=.
      - CONFIG_PATH=config/local
    ports:
      - "5555:5555"
    depends_on:
      - postgres_service
      - redis

volumes:
  postgres-data:
    driver: local
