apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricingportal-server
  labels:
    app: pricingportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricingportal
  template:
    metadata:
      labels:
        app: pricingportal
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: 921289669923.dkr.ecr.us-east-1.amazonaws.com/pricingportal/server:pricingportal-dev-3
          env:
          lifecycle:
            preStop:
              httpGet:
                path: "/api/health/down/"
                port: 5000
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: "/api/health/check/"
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: pricingportal-config
              mountPath: "/etc/uwsgi.ini"
              subPath: uwsgi.ini
              readOnly: true
            - name: pricingportal-config
              mountPath: "/etc/config/app.properties"
              subPath: app.properties
              readOnly: true
            - name: pricingportal-config
              mountPath: "/etc/config/env.sh"
              subPath: env.sh
              readOnly: true
            - name: pricingportal-secrets
              mountPath: "/etc/config/secrets.properties"
              subPath: secrets.properties
              readOnly: true
          ports:
            - containerPort: 5000
      volumes:
        - name: pricingportal-config
          configMap:
            name: pricingportal-config
        - name: pricingportal-secrets
          secret:
            secretName: pricingportal-secrets
